### ISSUE TITLE
No code action for imports

### ISSUE THREAD

**Issue by vushu** [Pure-D/serve-d#144]
Hi again sadly I still have some problems with code-actions for dub packages using serve-d

![image](https://user-images.githubusercontent.com/1658625/122755563-7207b580-d295-11eb-8ae8-a8c6f27f16b7.png)

using visual code with code-d works fine on the same project.

![image](https://user-images.githubusercontent.com/1658625/122756189-61a40a80-d296-11eb-9914-258815527250.png)

I am missing some setup I guess.

thanks.

**Comment by WebFreak001** [comment]
the import code action uses a custom command (because there is no way to just have the import as standard LSP stuff)

https://github.com/Pure-D/serve-d/blob/f191f1baefa9693c3840d8597a807ed0c2b98954/source/served/commands/code_actions.d#L101

You will need to register a command called "code-d.addImport" in your plugin for this action to work. Registering it might also make the LSP client library display the command, though I'm not sure about that.

For the implementation of the command you can refer to https://github.com/Pure-D/code-d/blob/704d916b8655ec538814dc82689777ee36d1bd60/src/commands.ts#L222

It does:

1. send a LSP request "served/addImport", passing the arguments you got in the addImport command as-is + send the current document URI (might make sense to already send this from serve-d too)
	* this is done because commands call stuff on the LSP client, I can't make code actions immediately execute serve-d commands
2. apply the modifications returned by serve-d

See https://github.com/Pure-D/serve-d#request-servedaddimport for information about the command

**Comment by vushu** [comment]
Hi @WebFreak001 

I have already implemented the command "code-d.addImport" , it does work, but only code actions for std library are showing up,  only code actions for external libraries aren't showing.

![image](https://user-images.githubusercontent.com/1658625/122762515-af704100-d29d-11eb-8015-ba2b8eeeb319.png)

Here is my implementation:
https://github.com/vushu/coc-dlang/blob/defbcdab90cf9c65e784fc468393900a3f07ec92/src/commands.ts

**Comment by WebFreak001** [comment]
ah right, the library symbols is a little bit unstable anyway, I will need to fix that in the future. I'm not sure why it even works in your vscode screenshot right now but if the std.stdio thing works (coming from the compiler), it should be easier to fix for other symbols in the future.

**Comment by vushu** [comment]
I dont know either :), so I can understand that this isn't fully supported yet, I will be looking forward to it then.

**Comment by WebFreak001** [comment]
new release better implements this, if with current nightly it still doesn't work, please reopen.
